name: Build Site

on:
  workflow_dispatch:
  
jobs:
  build_and_check:
    name: Zola Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Fetch & Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.18.0

      - name: Zola Build 
        run: |
          zola build