name: Zola CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  z-build:
    name: Zola Build

    steps:
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.18.0
        env:
          CLICOLOR_FORCE=1
        run: zola build