name: Build Site

on:
  workflow_dispatch:
  
jobs:
  build_and_check:
    name: Zola Build & Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Site Source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Fetch & Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.18.0

      - name: Zola Build 
        run: |
          pwd
          ls
          zola build